### ISSUE TITLE
Plugin returns 500 when app has lots of instances

### ISSUE THREAD

**Issue by stigtermichiel** [cloudfoundry/cpu-entitlement-plugin#29] opened 2020-07-08 11:10 UTC
Hi there,

As the title says: I just tried the plugin and it works fine for apps with few (<8) instances. When trying:

`cf cpu-entitlement app-with-10-instances`

I get:
```
FAILED
unexpected status code 500
```

**Comment by stigtermichiel** [comment] 2020-07-08 11:23
I just saw the --debug option. It seems that it is the cumulative-usage-fetcher that is failing.

See error below:

```
{"timestamp":"2020-07-08T11:19:55.439634000Z","level":"error","source":"cpu-entitlement","message":"cpu-entitlement.run.create-application-report.cumulative-usage-fetcher.promql-failed","data":{"app":"app1","app-guid":"6e5c11ec-7253-4f0d-b724-20ed348b4ced","error":"unexpected status code 500","query":"absolute_usage{source_id=\"6e5c11ec-7253-4f0d-b724-20ed344ced\"} / absolute_entitlement{source_id=\"6e5c11ec-7253-4f0d-b724-20ed3b4ced\"}","session":"1.1.7"}}```

**Comment by kieron-pivotal** [comment] 2020-07-09 15:36
Hi @stigtermichiel 

From that debug line, I can see log-cache is returning that 500 error. Is it possible to get the log-cache logs (probably from the doppler deployment in /var/vcap/sys/log/log-cache)?

I'm having trouble reproducing this myself. Do you see the problem go away if you scale back down under 10. Or does the plugin fail persistently after the first failure?

Thanks, Kieron

**Comment by stigtermichiel** [comment] 2020-07-14 11:33
Hi @kieron-pivotal,

Sorry for the late reply but I did some digging. I tried to replicate the request to log-cache by making the following curl request:
```
time curl -q  -G --key /var/vcap/jobs/log-cache-cf-auth-proxy/config/certs/external.key --cert /var/vcap/jobs/log-cache-cf-auth-proxy/config/certs/external.crt --cacert /var/vcap/jobs/log-cache-cf-auth-proxy/config/certs/proxy_ca.crt https://localhost:8081/api/v1/query --data-urlencode 'query=absolute_usage{source_id="ef041717-a07f-4cae-8976-2f3801857bf7"} / absolute_entitlement{source_id="ef041717-a07f-4cae-8976-2f3801857bf7"}'
```
The  error that we get is this: 
```
{"status":"error","errorType":"internal","error":"context deadline exceeded"}
real	0m5.119s
user	0m0.044s
sys	0m0.024s
```

We saw that it seemed to be timing out after 5 sec. Changing the query timeout setting in the log-cache config did not seem to change anything. After that we did some further digging in the plugin-code and I think we found the culprit:

The code is creating a log-cache client with the following function:
```
func NewClient(addr string, opts ...ClientOption) *Client {
	c := &Client{
		addr: addr,
		httpClient: &http.Client{
			Timeout: 5 * time.Second,
		},
	}

	for _, o := range opts {
		o.configure(c)
	}

	return c
}
```

as you can see, the 5 second timeout is hardcoded there. Do you have any ideas how we can circumvent this?

Thanks alot, Michiel.


Btw, another question: Is it true that for this plugin to give the right metrics, `set-cpu-weight` needs to be set on the platform? It seems that without it, the plugin gives wrong metrics.

**Comment by kieron-pivotal** [comment] 2020-07-16 15:22
First, yes, you must use `set-cpu-weight`.

Regarding the timeouts. The plugin code uses the default http.Client, wrapped with a function to add an authorization header: https://github.com/cloudfoundry/cpu-entitlement-plugin/blob/f762ff4c4017d02fda57d3ad622d252a4145fc66/plugins/app_plugin.go#L156, so it's not using the 5 second timeout from the library.

The plugin is routed to the log-cache-cf-auth-proxy, which itself has a 5 second timeout: https://github.com/cloudfoundry/log-cache/blob/526a0fd20d0308de00e5a3018047219428e31653/cmd/cf-auth-proxy/main.go#L77.

So it looks like there's nothing we can do from the plugin side. The real solution is to find the performance issue in log-cache, or to increase those timeouts in the log-cache and proxy code.

**Comment by gcapizzi** [comment] 2020-07-16 15:24
Hey @stigtermichiel! It looks like this issue is not something that we can fix on our side, so I'll close this!

**Closed by gcapizzi** 2020-07-16 15:24 UTC
Labels: in progress
